version: "2"

run:
  timeout: 3m

linters:
  default: standard
  enable:
    - bodyclose
    - errname
    - errorlint
    - gosec
    - misspell
    - nilerr
    - noctx
    - prealloc
    - revive
    - unconvert
    - unparam

  settings:
    govet:
      enable-all: true
    revive:
      rules:
        - name: blank-imports
        - name: context-as-argument
        - name: dot-imports
        - name: error-return
        - name: error-strings
        - name: exported
        - name: increment-decrement
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: var-declaration
    errcheck:
      check-type-assertions: true
    gosec:
      excludes:
        - G115

  exclusions:
    generated: strict
    paths:
      - internal/database

formatters:
  enable:
    - gofumpt
  settings:
    gofumpt:
      extra-rules: true
