// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CoffeeBean struct {
	ID           pgtype.UUID        `json:"id"`
	UserID       pgtype.UUID        `json:"user_id"`
	Name         string             `json:"name"`
	Origin       pgtype.Text        `json:"origin"`
	RoastLevel   string             `json:"roast_level"`
	RoastDetail  pgtype.Text        `json:"roast_detail"`
	CurrentStock int32              `json:"current_stock"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type PurchaseHistory struct {
	ID            pgtype.UUID        `json:"id"`
	CoffeeBeanID  pgtype.UUID        `json:"coffee_bean_id"`
	UserID        pgtype.UUID        `json:"user_id"`
	PurchaseDate  pgtype.Date        `json:"purchase_date"`
	PurchasePrice pgtype.Numeric     `json:"purchase_price"`
	PurchaseStore pgtype.Text        `json:"purchase_store"`
	Quantity      int32              `json:"quantity"`
	Notes         pgtype.Text        `json:"notes"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type UsageHistory struct {
	ID           pgtype.UUID        `json:"id"`
	CoffeeBeanID pgtype.UUID        `json:"coffee_bean_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	UsageDate    pgtype.Date        `json:"usage_date"`
	Quantity     int32              `json:"quantity"`
	Notes        pgtype.Text        `json:"notes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID                  pgtype.UUID        `json:"id"`
	Email               pgtype.Text        `json:"email"`
	PasswordHash        pgtype.Text        `json:"password_hash"`
	Name                pgtype.Text        `json:"name"`
	LowStockThreshold   int32              `json:"low_stock_threshold"`
	NotificationEnabled bool               `json:"notification_enabled"`
	GramsPerCup         int32              `json:"grams_per_cup"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}
