// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountCoffeeBeansByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountPurchaseHistoriesByCoffeeBeanID(ctx context.Context, coffeeBeanID pgtype.UUID) (int64, error)
	CountUsageHistoriesByCoffeeBeanID(ctx context.Context, coffeeBeanID pgtype.UUID) (int64, error)
	CountUsageHistoriesByUserID(ctx context.Context, userID pgtype.UUID) (int64, error)
	// ============================================================================
	// Users Queries
	// ============================================================================
	CreateAnonymousUser(ctx context.Context, arg CreateAnonymousUserParams) (User, error)
	// ============================================================================
	// Coffee Beans Queries (without purchase fields)
	// ============================================================================
	CreateCoffeeBean(ctx context.Context, arg CreateCoffeeBeanParams) (CoffeeBean, error)
	// ============================================================================
	// Purchase History Queries (NEW)
	// ============================================================================
	CreatePurchaseHistory(ctx context.Context, arg CreatePurchaseHistoryParams) (PurchaseHistory, error)
	// ============================================================================
	// Usage History Queries
	// ============================================================================
	CreateUsageHistory(ctx context.Context, arg CreateUsageHistoryParams) (UsageHistory, error)
	DeletePurchaseHistory(ctx context.Context, arg DeletePurchaseHistoryParams) error
	DeleteUsageHistory(ctx context.Context, arg DeleteUsageHistoryParams) error
	GetCoffeeBeanByID(ctx context.Context, id pgtype.UUID) (CoffeeBean, error)
	GetCoffeeBeanByIDForUpdate(ctx context.Context, id pgtype.UUID) (CoffeeBean, error)
	GetLatestPurchaseHistoryByCoffeeBeanID(ctx context.Context, coffeeBeanID pgtype.UUID) (PurchaseHistory, error)
	GetPurchaseHistoriesByCoffeeBeanID(ctx context.Context, arg GetPurchaseHistoriesByCoffeeBeanIDParams) ([]PurchaseHistory, error)
	GetPurchaseHistoryByID(ctx context.Context, id pgtype.UUID) (PurchaseHistory, error)
	GetRecentUsageHistoryForConsumptionRate(ctx context.Context, arg GetRecentUsageHistoryForConsumptionRateParams) ([]GetRecentUsageHistoryForConsumptionRateRow, error)
	GetUsageHistoryByID(ctx context.Context, id pgtype.UUID) (UsageHistory, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	ListCoffeeBeansByUserID(ctx context.Context, arg ListCoffeeBeansByUserIDParams) ([]CoffeeBean, error)
	ListCoffeeBeansWithLatestPurchase(ctx context.Context, arg ListCoffeeBeansWithLatestPurchaseParams) ([]ListCoffeeBeansWithLatestPurchaseRow, error)
	ListPurchaseHistoriesByUserID(ctx context.Context, arg ListPurchaseHistoriesByUserIDParams) ([]ListPurchaseHistoriesByUserIDRow, error)
	ListUsageHistoriesByCoffeeBeanID(ctx context.Context, arg ListUsageHistoriesByCoffeeBeanIDParams) ([]UsageHistory, error)
	ListUsageHistoriesByUserID(ctx context.Context, arg ListUsageHistoriesByUserIDParams) ([]ListUsageHistoriesByUserIDRow, error)
	SoftDeleteCoffeeBean(ctx context.Context, arg SoftDeleteCoffeeBeanParams) error
	SoftDeleteUser(ctx context.Context, id pgtype.UUID) error
	UpdateCoffeeBean(ctx context.Context, arg UpdateCoffeeBeanParams) (CoffeeBean, error)
	UpdateCoffeeBeanStock(ctx context.Context, arg UpdateCoffeeBeanStockParams) (CoffeeBean, error)
	UpdatePurchaseHistory(ctx context.Context, arg UpdatePurchaseHistoryParams) (PurchaseHistory, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
