// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCoffeeBeansByUserID = `-- name: CountCoffeeBeansByUserID :one
SELECT COUNT(*) FROM coffee_beans
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountCoffeeBeansByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCoffeeBeansByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPurchaseHistoriesByCoffeeBeanID = `-- name: CountPurchaseHistoriesByCoffeeBeanID :one
SELECT COUNT(*) FROM purchase_history
WHERE coffee_bean_id = $1
`

func (q *Queries) CountPurchaseHistoriesByCoffeeBeanID(ctx context.Context, coffeeBeanID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPurchaseHistoriesByCoffeeBeanID, coffeeBeanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageHistoriesByCoffeeBeanID = `-- name: CountUsageHistoriesByCoffeeBeanID :one
SELECT COUNT(*) FROM usage_history
WHERE coffee_bean_id = $1
`

func (q *Queries) CountUsageHistoriesByCoffeeBeanID(ctx context.Context, coffeeBeanID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageHistoriesByCoffeeBeanID, coffeeBeanID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsageHistoriesByUserID = `-- name: CountUsageHistoriesByUserID :one
SELECT COUNT(*) FROM usage_history
WHERE user_id = $1
`

func (q *Queries) CountUsageHistoriesByUserID(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsageHistoriesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAnonymousUser = `-- name: CreateAnonymousUser :one

INSERT INTO users (id, low_stock_threshold, grams_per_cup)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, name, low_stock_threshold, grams_per_cup, created_at, updated_at, deleted_at
`

type CreateAnonymousUserParams struct {
	ID                pgtype.UUID `json:"id"`
	LowStockThreshold int32       `json:"low_stock_threshold"`
	GramsPerCup       int32       `json:"grams_per_cup"`
}

// ============================================================================
// Users Queries
// ============================================================================
func (q *Queries) CreateAnonymousUser(ctx context.Context, arg CreateAnonymousUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createAnonymousUser, arg.ID, arg.LowStockThreshold, arg.GramsPerCup)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.LowStockThreshold,
		&i.GramsPerCup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCoffeeBean = `-- name: CreateCoffeeBean :one

INSERT INTO coffee_beans (
    id, user_id, name, origin, roast_level, roast_detail, current_stock, notes
) VALUES ($1, $2, $3, $4, $5, $8, $6, $7)
RETURNING id, user_id, name, origin, roast_level, roast_detail, current_stock, notes, created_at, updated_at, deleted_at
`

type CreateCoffeeBeanParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Name         string      `json:"name"`
	Origin       pgtype.Text `json:"origin"`
	RoastLevel   string      `json:"roast_level"`
	CurrentStock int32       `json:"current_stock"`
	Notes        pgtype.Text `json:"notes"`
	RoastDetail  pgtype.Text `json:"roast_detail"`
}

// ============================================================================
// Coffee Beans Queries (without purchase fields)
// ============================================================================
func (q *Queries) CreateCoffeeBean(ctx context.Context, arg CreateCoffeeBeanParams) (CoffeeBean, error) {
	row := q.db.QueryRow(ctx, createCoffeeBean,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Origin,
		arg.RoastLevel,
		arg.CurrentStock,
		arg.Notes,
		arg.RoastDetail,
	)
	var i CoffeeBean
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Origin,
		&i.RoastLevel,
		&i.RoastDetail,
		&i.CurrentStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPurchaseHistory = `-- name: CreatePurchaseHistory :one

INSERT INTO purchase_history (
    coffee_bean_id, user_id, purchase_date, purchase_price,
    purchase_store, quantity, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, coffee_bean_id, user_id, purchase_date, purchase_price, purchase_store, quantity, notes, created_at
`

type CreatePurchaseHistoryParams struct {
	CoffeeBeanID  pgtype.UUID    `json:"coffee_bean_id"`
	UserID        pgtype.UUID    `json:"user_id"`
	PurchaseDate  pgtype.Date    `json:"purchase_date"`
	PurchasePrice pgtype.Numeric `json:"purchase_price"`
	PurchaseStore pgtype.Text    `json:"purchase_store"`
	Quantity      int32          `json:"quantity"`
	Notes         pgtype.Text    `json:"notes"`
}

// ============================================================================
// Purchase History Queries (NEW)
// ============================================================================
func (q *Queries) CreatePurchaseHistory(ctx context.Context, arg CreatePurchaseHistoryParams) (PurchaseHistory, error) {
	row := q.db.QueryRow(ctx, createPurchaseHistory,
		arg.CoffeeBeanID,
		arg.UserID,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.PurchaseStore,
		arg.Quantity,
		arg.Notes,
	)
	var i PurchaseHistory
	err := row.Scan(
		&i.ID,
		&i.CoffeeBeanID,
		&i.UserID,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.PurchaseStore,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// ============================================================================
// Refresh Tokens Queries
// ============================================================================
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createUsageHistory = `-- name: CreateUsageHistory :one

INSERT INTO usage_history (
    coffee_bean_id, user_id, usage_date, quantity, notes
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, coffee_bean_id, user_id, usage_date, quantity, notes, created_at
`

type CreateUsageHistoryParams struct {
	CoffeeBeanID pgtype.UUID `json:"coffee_bean_id"`
	UserID       pgtype.UUID `json:"user_id"`
	UsageDate    pgtype.Date `json:"usage_date"`
	Quantity     int32       `json:"quantity"`
	Notes        pgtype.Text `json:"notes"`
}

// ============================================================================
// Usage History Queries
// ============================================================================
func (q *Queries) CreateUsageHistory(ctx context.Context, arg CreateUsageHistoryParams) (UsageHistory, error) {
	row := q.db.QueryRow(ctx, createUsageHistory,
		arg.CoffeeBeanID,
		arg.UserID,
		arg.UsageDate,
		arg.Quantity,
		arg.Notes,
	)
	var i UsageHistory
	err := row.Scan(
		&i.ID,
		&i.CoffeeBeanID,
		&i.UserID,
		&i.UsageDate,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredRefreshTokens = `-- name: DeleteExpiredRefreshTokens :exec
DELETE FROM refresh_tokens
WHERE expires_at <= CURRENT_TIMESTAMP
`

func (q *Queries) DeleteExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRefreshTokens)
	return err
}

const deletePurchaseHistory = `-- name: DeletePurchaseHistory :exec
DELETE FROM purchase_history
WHERE id = $1 AND user_id = $2
`

type DeletePurchaseHistoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeletePurchaseHistory(ctx context.Context, arg DeletePurchaseHistoryParams) error {
	_, err := q.db.Exec(ctx, deletePurchaseHistory, arg.ID, arg.UserID)
	return err
}

const deleteRefreshTokenByHash = `-- name: DeleteRefreshTokenByHash :exec
DELETE FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByHash, tokenHash)
	return err
}

const deleteRefreshTokensByUserID = `-- name: DeleteRefreshTokensByUserID :exec
DELETE FROM refresh_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokensByUserID, userID)
	return err
}

const deleteUsageHistory = `-- name: DeleteUsageHistory :exec
DELETE FROM usage_history
WHERE id = $1 AND user_id = $2
`

type DeleteUsageHistoryParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteUsageHistory(ctx context.Context, arg DeleteUsageHistoryParams) error {
	_, err := q.db.Exec(ctx, deleteUsageHistory, arg.ID, arg.UserID)
	return err
}

const getCoffeeBeanByID = `-- name: GetCoffeeBeanByID :one
SELECT id, user_id, name, origin, roast_level, roast_detail, current_stock, notes, created_at, updated_at, deleted_at FROM coffee_beans
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetCoffeeBeanByID(ctx context.Context, id pgtype.UUID) (CoffeeBean, error) {
	row := q.db.QueryRow(ctx, getCoffeeBeanByID, id)
	var i CoffeeBean
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Origin,
		&i.RoastLevel,
		&i.RoastDetail,
		&i.CurrentStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCoffeeBeanByIDForUpdate = `-- name: GetCoffeeBeanByIDForUpdate :one
SELECT id, user_id, name, origin, roast_level, roast_detail, current_stock, notes, created_at, updated_at, deleted_at FROM coffee_beans
WHERE id = $1 AND deleted_at IS NULL
FOR UPDATE
`

func (q *Queries) GetCoffeeBeanByIDForUpdate(ctx context.Context, id pgtype.UUID) (CoffeeBean, error) {
	row := q.db.QueryRow(ctx, getCoffeeBeanByIDForUpdate, id)
	var i CoffeeBean
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Origin,
		&i.RoastLevel,
		&i.RoastDetail,
		&i.CurrentStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestPurchaseHistoryByCoffeeBeanID = `-- name: GetLatestPurchaseHistoryByCoffeeBeanID :one
SELECT id, coffee_bean_id, user_id, purchase_date, purchase_price, purchase_store, quantity, notes, created_at FROM purchase_history
WHERE coffee_bean_id = $1
ORDER BY purchase_date DESC, created_at DESC
LIMIT 1
`

func (q *Queries) GetLatestPurchaseHistoryByCoffeeBeanID(ctx context.Context, coffeeBeanID pgtype.UUID) (PurchaseHistory, error) {
	row := q.db.QueryRow(ctx, getLatestPurchaseHistoryByCoffeeBeanID, coffeeBeanID)
	var i PurchaseHistory
	err := row.Scan(
		&i.ID,
		&i.CoffeeBeanID,
		&i.UserID,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.PurchaseStore,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getPurchaseHistoriesByCoffeeBeanID = `-- name: GetPurchaseHistoriesByCoffeeBeanID :many
SELECT id, coffee_bean_id, user_id, purchase_date, purchase_price, purchase_store, quantity, notes, created_at FROM purchase_history
WHERE coffee_bean_id = $1
ORDER BY purchase_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type GetPurchaseHistoriesByCoffeeBeanIDParams struct {
	CoffeeBeanID pgtype.UUID `json:"coffee_bean_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) GetPurchaseHistoriesByCoffeeBeanID(ctx context.Context, arg GetPurchaseHistoriesByCoffeeBeanIDParams) ([]PurchaseHistory, error) {
	rows, err := q.db.Query(ctx, getPurchaseHistoriesByCoffeeBeanID, arg.CoffeeBeanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PurchaseHistory{}
	for rows.Next() {
		var i PurchaseHistory
		if err := rows.Scan(
			&i.ID,
			&i.CoffeeBeanID,
			&i.UserID,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.PurchaseStore,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseHistoryByID = `-- name: GetPurchaseHistoryByID :one
SELECT id, coffee_bean_id, user_id, purchase_date, purchase_price, purchase_store, quantity, notes, created_at FROM purchase_history
WHERE id = $1
`

func (q *Queries) GetPurchaseHistoryByID(ctx context.Context, id pgtype.UUID) (PurchaseHistory, error) {
	row := q.db.QueryRow(ctx, getPurchaseHistoryByID, id)
	var i PurchaseHistory
	err := row.Scan(
		&i.ID,
		&i.CoffeeBeanID,
		&i.UserID,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.PurchaseStore,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getRecentUsageHistoryForConsumptionRate = `-- name: GetRecentUsageHistoryForConsumptionRate :many
SELECT usage_date, quantity
FROM usage_history
WHERE coffee_bean_id = $1 AND usage_date >= $2
ORDER BY usage_date DESC
`

type GetRecentUsageHistoryForConsumptionRateParams struct {
	CoffeeBeanID pgtype.UUID `json:"coffee_bean_id"`
	UsageDate    pgtype.Date `json:"usage_date"`
}

type GetRecentUsageHistoryForConsumptionRateRow struct {
	UsageDate pgtype.Date `json:"usage_date"`
	Quantity  int32       `json:"quantity"`
}

func (q *Queries) GetRecentUsageHistoryForConsumptionRate(ctx context.Context, arg GetRecentUsageHistoryForConsumptionRateParams) ([]GetRecentUsageHistoryForConsumptionRateRow, error) {
	rows, err := q.db.Query(ctx, getRecentUsageHistoryForConsumptionRate, arg.CoffeeBeanID, arg.UsageDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentUsageHistoryForConsumptionRateRow{}
	for rows.Next() {
		var i GetRecentUsageHistoryForConsumptionRateRow
		if err := rows.Scan(&i.UsageDate, &i.Quantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentUsageSummaryByUserID = `-- name: GetRecentUsageSummaryByUserID :many
SELECT coffee_bean_id, COALESCE(SUM(quantity), 0)::int AS total_quantity
FROM usage_history
WHERE user_id = $1 AND usage_date >= $2
GROUP BY coffee_bean_id
`

type GetRecentUsageSummaryByUserIDParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	UsageDate pgtype.Date `json:"usage_date"`
}

type GetRecentUsageSummaryByUserIDRow struct {
	CoffeeBeanID  pgtype.UUID `json:"coffee_bean_id"`
	TotalQuantity int32       `json:"total_quantity"`
}

func (q *Queries) GetRecentUsageSummaryByUserID(ctx context.Context, arg GetRecentUsageSummaryByUserIDParams) ([]GetRecentUsageSummaryByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getRecentUsageSummaryByUserID, arg.UserID, arg.UsageDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRecentUsageSummaryByUserIDRow{}
	for rows.Next() {
		var i GetRecentUsageSummaryByUserIDRow
		if err := rows.Scan(&i.CoffeeBeanID, &i.TotalQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, expires_at, created_at FROM refresh_tokens
WHERE token_hash = $1 AND expires_at > CURRENT_TIMESTAMP
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getUsageHistoryByID = `-- name: GetUsageHistoryByID :one
SELECT id, coffee_bean_id, user_id, usage_date, quantity, notes, created_at FROM usage_history
WHERE id = $1
`

func (q *Queries) GetUsageHistoryByID(ctx context.Context, id pgtype.UUID) (UsageHistory, error) {
	row := q.db.QueryRow(ctx, getUsageHistoryByID, id)
	var i UsageHistory
	err := row.Scan(
		&i.ID,
		&i.CoffeeBeanID,
		&i.UserID,
		&i.UsageDate,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, low_stock_threshold, grams_per_cup, created_at, updated_at, deleted_at FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.LowStockThreshold,
		&i.GramsPerCup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listCoffeeBeansByUserID = `-- name: ListCoffeeBeansByUserID :many
SELECT id, user_id, name, origin, roast_level, roast_detail, current_stock, notes, created_at, updated_at, deleted_at FROM coffee_beans
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC
LIMIT $2 OFFSET $3
`

type ListCoffeeBeansByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListCoffeeBeansByUserID(ctx context.Context, arg ListCoffeeBeansByUserIDParams) ([]CoffeeBean, error) {
	rows, err := q.db.Query(ctx, listCoffeeBeansByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CoffeeBean{}
	for rows.Next() {
		var i CoffeeBean
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Origin,
			&i.RoastLevel,
			&i.RoastDetail,
			&i.CurrentStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCoffeeBeansWithLatestPurchase = `-- name: ListCoffeeBeansWithLatestPurchase :many
SELECT
    cb.id,
    cb.user_id,
    cb.name,
    cb.origin,
    cb.roast_level,
    cb.roast_detail,
    cb.current_stock,
    cb.notes,
    cb.created_at,
    cb.updated_at,
    cb.deleted_at,
    ph.purchase_date as latest_purchase_date,
    ph.purchase_price as latest_purchase_price,
    ph.purchase_store as latest_purchase_store
FROM coffee_beans cb
LEFT JOIN LATERAL (
    SELECT purchase_date, purchase_price, purchase_store
    FROM purchase_history
    WHERE coffee_bean_id = cb.id
    ORDER BY purchase_date DESC, created_at DESC
    LIMIT 1
) ph ON true
WHERE cb.user_id = $1 AND cb.deleted_at IS NULL
ORDER BY cb.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListCoffeeBeansWithLatestPurchaseParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListCoffeeBeansWithLatestPurchaseRow struct {
	ID                  pgtype.UUID        `json:"id"`
	UserID              pgtype.UUID        `json:"user_id"`
	Name                string             `json:"name"`
	Origin              pgtype.Text        `json:"origin"`
	RoastLevel          string             `json:"roast_level"`
	RoastDetail         pgtype.Text        `json:"roast_detail"`
	CurrentStock        int32              `json:"current_stock"`
	Notes               pgtype.Text        `json:"notes"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
	LatestPurchaseDate  pgtype.Date        `json:"latest_purchase_date"`
	LatestPurchasePrice pgtype.Numeric     `json:"latest_purchase_price"`
	LatestPurchaseStore pgtype.Text        `json:"latest_purchase_store"`
}

func (q *Queries) ListCoffeeBeansWithLatestPurchase(ctx context.Context, arg ListCoffeeBeansWithLatestPurchaseParams) ([]ListCoffeeBeansWithLatestPurchaseRow, error) {
	rows, err := q.db.Query(ctx, listCoffeeBeansWithLatestPurchase, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCoffeeBeansWithLatestPurchaseRow{}
	for rows.Next() {
		var i ListCoffeeBeansWithLatestPurchaseRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Origin,
			&i.RoastLevel,
			&i.RoastDetail,
			&i.CurrentStock,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.LatestPurchaseDate,
			&i.LatestPurchasePrice,
			&i.LatestPurchaseStore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseHistoriesByUserID = `-- name: ListPurchaseHistoriesByUserID :many
SELECT ph.id, ph.coffee_bean_id, ph.user_id, ph.purchase_date, ph.purchase_price, ph.purchase_store, ph.quantity, ph.notes, ph.created_at, cb.name as coffee_bean_name
FROM purchase_history ph
JOIN coffee_beans cb ON ph.coffee_bean_id = cb.id
WHERE ph.user_id = $1
ORDER BY ph.purchase_date DESC, ph.created_at DESC
LIMIT $2 OFFSET $3
`

type ListPurchaseHistoriesByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListPurchaseHistoriesByUserIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	CoffeeBeanID   pgtype.UUID        `json:"coffee_bean_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	PurchaseDate   pgtype.Date        `json:"purchase_date"`
	PurchasePrice  pgtype.Numeric     `json:"purchase_price"`
	PurchaseStore  pgtype.Text        `json:"purchase_store"`
	Quantity       int32              `json:"quantity"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CoffeeBeanName string             `json:"coffee_bean_name"`
}

func (q *Queries) ListPurchaseHistoriesByUserID(ctx context.Context, arg ListPurchaseHistoriesByUserIDParams) ([]ListPurchaseHistoriesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseHistoriesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPurchaseHistoriesByUserIDRow{}
	for rows.Next() {
		var i ListPurchaseHistoriesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CoffeeBeanID,
			&i.UserID,
			&i.PurchaseDate,
			&i.PurchasePrice,
			&i.PurchaseStore,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
			&i.CoffeeBeanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageHistoriesByCoffeeBeanID = `-- name: ListUsageHistoriesByCoffeeBeanID :many
SELECT id, coffee_bean_id, user_id, usage_date, quantity, notes, created_at FROM usage_history
WHERE coffee_bean_id = $1
ORDER BY usage_date DESC, created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageHistoriesByCoffeeBeanIDParams struct {
	CoffeeBeanID pgtype.UUID `json:"coffee_bean_id"`
	Limit        int32       `json:"limit"`
	Offset       int32       `json:"offset"`
}

func (q *Queries) ListUsageHistoriesByCoffeeBeanID(ctx context.Context, arg ListUsageHistoriesByCoffeeBeanIDParams) ([]UsageHistory, error) {
	rows, err := q.db.Query(ctx, listUsageHistoriesByCoffeeBeanID, arg.CoffeeBeanID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UsageHistory{}
	for rows.Next() {
		var i UsageHistory
		if err := rows.Scan(
			&i.ID,
			&i.CoffeeBeanID,
			&i.UserID,
			&i.UsageDate,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageHistoriesByUserID = `-- name: ListUsageHistoriesByUserID :many
SELECT uh.id, uh.coffee_bean_id, uh.user_id, uh.usage_date, uh.quantity, uh.notes, uh.created_at, cb.name as coffee_bean_name
FROM usage_history uh
JOIN coffee_beans cb ON uh.coffee_bean_id = cb.id
WHERE uh.user_id = $1 AND cb.deleted_at IS NULL
ORDER BY uh.usage_date DESC, uh.created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsageHistoriesByUserIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type ListUsageHistoriesByUserIDRow struct {
	ID             pgtype.UUID        `json:"id"`
	CoffeeBeanID   pgtype.UUID        `json:"coffee_bean_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	UsageDate      pgtype.Date        `json:"usage_date"`
	Quantity       int32              `json:"quantity"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	CoffeeBeanName string             `json:"coffee_bean_name"`
}

func (q *Queries) ListUsageHistoriesByUserID(ctx context.Context, arg ListUsageHistoriesByUserIDParams) ([]ListUsageHistoriesByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listUsageHistoriesByUserID, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsageHistoriesByUserIDRow{}
	for rows.Next() {
		var i ListUsageHistoriesByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CoffeeBeanID,
			&i.UserID,
			&i.UsageDate,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
			&i.CoffeeBeanName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteCoffeeBean = `-- name: SoftDeleteCoffeeBean :exec
UPDATE coffee_beans
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteCoffeeBeanParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteCoffeeBean(ctx context.Context, arg SoftDeleteCoffeeBeanParams) error {
	_, err := q.db.Exec(ctx, softDeleteCoffeeBean, arg.ID, arg.UserID)
	return err
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateCoffeeBean = `-- name: UpdateCoffeeBean :one
UPDATE coffee_beans
SET
    name = COALESCE($3, name),
    origin = COALESCE($4, origin),
    roast_level = COALESCE($5, roast_level),
    roast_detail = COALESCE($6, roast_detail),
    current_stock = COALESCE($7, current_stock),
    notes = COALESCE($8, notes),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
RETURNING id, user_id, name, origin, roast_level, roast_detail, current_stock, notes, created_at, updated_at, deleted_at
`

type UpdateCoffeeBeanParams struct {
	ID           pgtype.UUID `json:"id"`
	UserID       pgtype.UUID `json:"user_id"`
	Name         pgtype.Text `json:"name"`
	Origin       pgtype.Text `json:"origin"`
	RoastLevel   pgtype.Text `json:"roast_level"`
	RoastDetail  pgtype.Text `json:"roast_detail"`
	CurrentStock pgtype.Int4 `json:"current_stock"`
	Notes        pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateCoffeeBean(ctx context.Context, arg UpdateCoffeeBeanParams) (CoffeeBean, error) {
	row := q.db.QueryRow(ctx, updateCoffeeBean,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Origin,
		arg.RoastLevel,
		arg.RoastDetail,
		arg.CurrentStock,
		arg.Notes,
	)
	var i CoffeeBean
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Origin,
		&i.RoastLevel,
		&i.RoastDetail,
		&i.CurrentStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateCoffeeBeanStock = `-- name: UpdateCoffeeBeanStock :one
UPDATE coffee_beans
SET
    current_stock = $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, name, origin, roast_level, roast_detail, current_stock, notes, created_at, updated_at, deleted_at
`

type UpdateCoffeeBeanStockParams struct {
	ID           pgtype.UUID `json:"id"`
	CurrentStock int32       `json:"current_stock"`
}

func (q *Queries) UpdateCoffeeBeanStock(ctx context.Context, arg UpdateCoffeeBeanStockParams) (CoffeeBean, error) {
	row := q.db.QueryRow(ctx, updateCoffeeBeanStock, arg.ID, arg.CurrentStock)
	var i CoffeeBean
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Origin,
		&i.RoastLevel,
		&i.RoastDetail,
		&i.CurrentStock,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updatePurchaseHistory = `-- name: UpdatePurchaseHistory :one
UPDATE purchase_history
SET
    purchase_date = COALESCE($3, purchase_date),
    purchase_price = COALESCE($4, purchase_price),
    purchase_store = COALESCE($5, purchase_store),
    quantity = COALESCE($6, quantity),
    notes = COALESCE($7, notes)
WHERE id = $1 AND user_id = $2
RETURNING id, coffee_bean_id, user_id, purchase_date, purchase_price, purchase_store, quantity, notes, created_at
`

type UpdatePurchaseHistoryParams struct {
	ID            pgtype.UUID    `json:"id"`
	UserID        pgtype.UUID    `json:"user_id"`
	PurchaseDate  pgtype.Date    `json:"purchase_date"`
	PurchasePrice pgtype.Numeric `json:"purchase_price"`
	PurchaseStore pgtype.Text    `json:"purchase_store"`
	Quantity      pgtype.Int4    `json:"quantity"`
	Notes         pgtype.Text    `json:"notes"`
}

func (q *Queries) UpdatePurchaseHistory(ctx context.Context, arg UpdatePurchaseHistoryParams) (PurchaseHistory, error) {
	row := q.db.QueryRow(ctx, updatePurchaseHistory,
		arg.ID,
		arg.UserID,
		arg.PurchaseDate,
		arg.PurchasePrice,
		arg.PurchaseStore,
		arg.Quantity,
		arg.Notes,
	)
	var i PurchaseHistory
	err := row.Scan(
		&i.ID,
		&i.CoffeeBeanID,
		&i.UserID,
		&i.PurchaseDate,
		&i.PurchasePrice,
		&i.PurchaseStore,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
    name = COALESCE($2, name),
    low_stock_threshold = COALESCE($3, low_stock_threshold),
    grams_per_cup = COALESCE($4, grams_per_cup),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, password_hash, name, low_stock_threshold, grams_per_cup, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID                pgtype.UUID `json:"id"`
	Name              pgtype.Text `json:"name"`
	LowStockThreshold pgtype.Int4 `json:"low_stock_threshold"`
	GramsPerCup       pgtype.Int4 `json:"grams_per_cup"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.LowStockThreshold,
		arg.GramsPerCup,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.LowStockThreshold,
		&i.GramsPerCup,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
