// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/unitofwork/unitofwork.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/unitofwork/unitofwork.go -destination=internal/usecase/mock/mock_unitofwork.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	coffeebean "github.com/k3forx/CoffeeBeansStock/backend/internal/domain/coffeebean"
	unitofwork "github.com/k3forx/CoffeeBeansStock/backend/internal/domain/unitofwork"
	usagehistory "github.com/k3forx/CoffeeBeansStock/backend/internal/domain/usagehistory"
	user "github.com/k3forx/CoffeeBeansStock/backend/internal/domain/user"
	gomock "go.uber.org/mock/gomock"
)

// MockUnitOfWork is a mock of UnitOfWork interface.
type MockUnitOfWork struct {
	ctrl     *gomock.Controller
	recorder *MockUnitOfWorkMockRecorder
	isgomock struct{}
}

// MockUnitOfWorkMockRecorder is the mock recorder for MockUnitOfWork.
type MockUnitOfWorkMockRecorder struct {
	mock *MockUnitOfWork
}

// NewMockUnitOfWork creates a new mock instance.
func NewMockUnitOfWork(ctrl *gomock.Controller) *MockUnitOfWork {
	mock := &MockUnitOfWork{ctrl: ctrl}
	mock.recorder = &MockUnitOfWorkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnitOfWork) EXPECT() *MockUnitOfWorkMockRecorder {
	return m.recorder
}

// RunInTx mocks base method.
func (m *MockUnitOfWork) RunInTx(ctx context.Context, fn func(unitofwork.Store) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunInTx", ctx, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunInTx indicates an expected call of RunInTx.
func (mr *MockUnitOfWorkMockRecorder) RunInTx(ctx, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunInTx", reflect.TypeOf((*MockUnitOfWork)(nil).RunInTx), ctx, fn)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// CoffeeBeanRepo mocks base method.
func (m *MockStore) CoffeeBeanRepo() coffeebean.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CoffeeBeanRepo")
	ret0, _ := ret[0].(coffeebean.Repository)
	return ret0
}

// CoffeeBeanRepo indicates an expected call of CoffeeBeanRepo.
func (mr *MockStoreMockRecorder) CoffeeBeanRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CoffeeBeanRepo", reflect.TypeOf((*MockStore)(nil).CoffeeBeanRepo))
}

// UsageHistoryRepo mocks base method.
func (m *MockStore) UsageHistoryRepo() usagehistory.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UsageHistoryRepo")
	ret0, _ := ret[0].(usagehistory.Repository)
	return ret0
}

// UsageHistoryRepo indicates an expected call of UsageHistoryRepo.
func (mr *MockStoreMockRecorder) UsageHistoryRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UsageHistoryRepo", reflect.TypeOf((*MockStore)(nil).UsageHistoryRepo))
}

// UserRepo mocks base method.
func (m *MockStore) UserRepo() user.Repository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserRepo")
	ret0, _ := ret[0].(user.Repository)
	return ret0
}

// UserRepo indicates an expected call of UserRepo.
func (mr *MockStoreMockRecorder) UserRepo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserRepo", reflect.TypeOf((*MockStore)(nil).UserRepo))
}
