// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/usagehistory/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/usagehistory/repository.go -destination=internal/usecase/mock/mock_usagehistory_repository.go -package=mock -mock_names=Repository=MockUsageHistoryRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	usagehistory "github.com/k3forx/CoffeeBeansStock/backend/internal/domain/usagehistory"
	gomock "go.uber.org/mock/gomock"
)

// MockUsageHistoryRepository is a mock of Repository interface.
type MockUsageHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUsageHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockUsageHistoryRepositoryMockRecorder is the mock recorder for MockUsageHistoryRepository.
type MockUsageHistoryRepositoryMockRecorder struct {
	mock *MockUsageHistoryRepository
}

// NewMockUsageHistoryRepository creates a new mock instance.
func NewMockUsageHistoryRepository(ctrl *gomock.Controller) *MockUsageHistoryRepository {
	mock := &MockUsageHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockUsageHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsageHistoryRepository) EXPECT() *MockUsageHistoryRepositoryMockRecorder {
	return m.recorder
}

// CountByCoffeeBeanID mocks base method.
func (m *MockUsageHistoryRepository) CountByCoffeeBeanID(ctx context.Context, coffeeBeanID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByCoffeeBeanID", ctx, coffeeBeanID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByCoffeeBeanID indicates an expected call of CountByCoffeeBeanID.
func (mr *MockUsageHistoryRepositoryMockRecorder) CountByCoffeeBeanID(ctx, coffeeBeanID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByCoffeeBeanID", reflect.TypeOf((*MockUsageHistoryRepository)(nil).CountByCoffeeBeanID), ctx, coffeeBeanID)
}

// Delete mocks base method.
func (m *MockUsageHistoryRepository) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsageHistoryRepositoryMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsageHistoryRepository)(nil).Delete), ctx, id, userID)
}

// GetByID mocks base method.
func (m *MockUsageHistoryRepository) GetByID(ctx context.Context, id uuid.UUID) (*usagehistory.UsageHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*usagehistory.UsageHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsageHistoryRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsageHistoryRepository)(nil).GetByID), ctx, id)
}

// GetRecentUsageSummary mocks base method.
func (m *MockUsageHistoryRepository) GetRecentUsageSummary(ctx context.Context, coffeeBeanID uuid.UUID, since time.Time) (int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentUsageSummary", ctx, coffeeBeanID, since)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentUsageSummary indicates an expected call of GetRecentUsageSummary.
func (mr *MockUsageHistoryRepositoryMockRecorder) GetRecentUsageSummary(ctx, coffeeBeanID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentUsageSummary", reflect.TypeOf((*MockUsageHistoryRepository)(nil).GetRecentUsageSummary), ctx, coffeeBeanID, since)
}

// GetRecentUsageSummaryByUserID mocks base method.
func (m *MockUsageHistoryRepository) GetRecentUsageSummaryByUserID(ctx context.Context, userID uuid.UUID, since time.Time) (map[uuid.UUID]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentUsageSummaryByUserID", ctx, userID, since)
	ret0, _ := ret[0].(map[uuid.UUID]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentUsageSummaryByUserID indicates an expected call of GetRecentUsageSummaryByUserID.
func (mr *MockUsageHistoryRepositoryMockRecorder) GetRecentUsageSummaryByUserID(ctx, userID, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentUsageSummaryByUserID", reflect.TypeOf((*MockUsageHistoryRepository)(nil).GetRecentUsageSummaryByUserID), ctx, userID, since)
}

// ListByCoffeeBeanID mocks base method.
func (m *MockUsageHistoryRepository) ListByCoffeeBeanID(ctx context.Context, coffeeBeanID uuid.UUID, limit, offset int32) ([]*usagehistory.UsageHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCoffeeBeanID", ctx, coffeeBeanID, limit, offset)
	ret0, _ := ret[0].([]*usagehistory.UsageHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCoffeeBeanID indicates an expected call of ListByCoffeeBeanID.
func (mr *MockUsageHistoryRepositoryMockRecorder) ListByCoffeeBeanID(ctx, coffeeBeanID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCoffeeBeanID", reflect.TypeOf((*MockUsageHistoryRepository)(nil).ListByCoffeeBeanID), ctx, coffeeBeanID, limit, offset)
}

// Save mocks base method.
func (m *MockUsageHistoryRepository) Save(ctx context.Context, usage *usagehistory.UsageHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, usage)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUsageHistoryRepositoryMockRecorder) Save(ctx, usage any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUsageHistoryRepository)(nil).Save), ctx, usage)
}
