// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/coffeebean/repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/coffeebean/repository.go -destination=internal/usecase/mock/mock_coffeebean_repository.go -package=mock -mock_names Repository=MockCoffeeBeanRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	coffeebean "github.com/k3forx/CoffeeBeansStock/backend/internal/domain/coffeebean"
	gomock "go.uber.org/mock/gomock"
)

// MockCoffeeBeanRepository is a mock of Repository interface.
type MockCoffeeBeanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCoffeeBeanRepositoryMockRecorder
	isgomock struct{}
}

// MockCoffeeBeanRepositoryMockRecorder is the mock recorder for MockCoffeeBeanRepository.
type MockCoffeeBeanRepositoryMockRecorder struct {
	mock *MockCoffeeBeanRepository
}

// NewMockCoffeeBeanRepository creates a new mock instance.
func NewMockCoffeeBeanRepository(ctrl *gomock.Controller) *MockCoffeeBeanRepository {
	mock := &MockCoffeeBeanRepository{ctrl: ctrl}
	mock.recorder = &MockCoffeeBeanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoffeeBeanRepository) EXPECT() *MockCoffeeBeanRepositoryMockRecorder {
	return m.recorder
}

// CountByUserID mocks base method.
func (m *MockCoffeeBeanRepository) CountByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByUserID", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByUserID indicates an expected call of CountByUserID.
func (mr *MockCoffeeBeanRepositoryMockRecorder) CountByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByUserID", reflect.TypeOf((*MockCoffeeBeanRepository)(nil).CountByUserID), ctx, userID)
}

// GetByID mocks base method.
func (m *MockCoffeeBeanRepository) GetByID(ctx context.Context, id uuid.UUID) (*coffeebean.CoffeeBean, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*coffeebean.CoffeeBean)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCoffeeBeanRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCoffeeBeanRepository)(nil).GetByID), ctx, id)
}

// GetByIDForUpdate mocks base method.
func (m *MockCoffeeBeanRepository) GetByIDForUpdate(ctx context.Context, id uuid.UUID) (*coffeebean.CoffeeBean, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDForUpdate", ctx, id)
	ret0, _ := ret[0].(*coffeebean.CoffeeBean)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDForUpdate indicates an expected call of GetByIDForUpdate.
func (mr *MockCoffeeBeanRepositoryMockRecorder) GetByIDForUpdate(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDForUpdate", reflect.TypeOf((*MockCoffeeBeanRepository)(nil).GetByIDForUpdate), ctx, id)
}

// ListByUserID mocks base method.
func (m *MockCoffeeBeanRepository) ListByUserID(ctx context.Context, userID uuid.UUID, limit, offset int32) ([]*coffeebean.CoffeeBean, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*coffeebean.CoffeeBean)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockCoffeeBeanRepositoryMockRecorder) ListByUserID(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockCoffeeBeanRepository)(nil).ListByUserID), ctx, userID, limit, offset)
}

// Save mocks base method.
func (m *MockCoffeeBeanRepository) Save(ctx context.Context, bean *coffeebean.CoffeeBean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, bean)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockCoffeeBeanRepositoryMockRecorder) Save(ctx, bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockCoffeeBeanRepository)(nil).Save), ctx, bean)
}

// SoftDelete mocks base method.
func (m *MockCoffeeBeanRepository) SoftDelete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockCoffeeBeanRepositoryMockRecorder) SoftDelete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockCoffeeBeanRepository)(nil).SoftDelete), ctx, id, userID)
}

// Update mocks base method.
func (m *MockCoffeeBeanRepository) Update(ctx context.Context, bean *coffeebean.CoffeeBean) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, bean)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCoffeeBeanRepositoryMockRecorder) Update(ctx, bean any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCoffeeBeanRepository)(nil).Update), ctx, bean)
}
