/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ヘルスチェック */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 匿名ユーザー登録 */
        post: operations["registerAnonymous"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** トークンリフレッシュ */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 認証ユーザー情報取得 */
        get: operations["getMe"];
        /** ユーザー設定更新 */
        put: operations["updateMe"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffee-beans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** コーヒー豆一覧取得 */
        get: operations["listBeans"];
        put?: never;
        /** コーヒー豆登録 */
        post: operations["createBean"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffee-beans/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** コーヒー豆詳細取得 */
        get: operations["getBean"];
        /** コーヒー豆更新 */
        put: operations["updateBean"];
        post?: never;
        /** コーヒー豆削除 */
        delete: operations["deleteBean"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffee-beans/{id}/usages": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** 使用記録一覧取得 */
        get: operations["listUsageHistories"];
        put?: never;
        /** 使用記録作成 */
        post: operations["createUsageHistory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coffee-beans/{id}/usages/{usageId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                usageId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 使用記録削除 */
        delete: operations["deleteUsageHistory"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UserResponse: {
            /** Format: uuid */
            id: string;
            name?: string;
            /** Format: int32 */
            low_stock_threshold?: number;
            notification_enabled?: boolean;
            /** Format: int32 */
            grams_per_cup?: number;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        AuthResponse: {
            user: components["schemas"]["UserResponse"];
            access_token: string;
            refresh_token: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        RefreshResult: {
            access_token: string;
            refresh_token: string;
        };
        UpdateUserRequest: {
            /** Format: int32 */
            low_stock_threshold?: number;
            notification_enabled?: boolean;
            /** Format: int32 */
            grams_per_cup?: number;
        };
        /** @enum {string} */
        RoastLevel: "shallow" | "medium" | "medium_deep" | "deep";
        /** @enum {string} */
        RoastDetail: "light" | "cinnamon" | "medium" | "high" | "city" | "full_city" | "french" | "italian";
        ConsumptionRate: {
            /**
             * Format: int32
             * @description 残杯数（設定ベース）
             */
            remaining_cups: number;
            /**
             * Format: int32
             * @description 残日数（履歴ベース、データ不足時はnull）
             */
            remaining_days?: number;
            /**
             * Format: float
             * @description 1日あたりの消費量 (g)
             */
            daily_consumption_grams?: number;
            /**
             * Format: int32
             * @description 直近7日間の合計消費量 (g)
             */
            weekly_total_grams?: number;
        };
        CoffeeBeanResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            origin?: string;
            roast_level: components["schemas"]["RoastLevel"];
            roast_detail?: components["schemas"]["RoastDetail"];
            /** Format: int32 */
            current_stock: number;
            consumption_rate: components["schemas"]["ConsumptionRate"];
            notes?: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateBeanRequest: {
            name: string;
            origin?: string;
            roast_level: components["schemas"]["RoastLevel"];
            roast_detail?: components["schemas"]["RoastDetail"];
            /** Format: int32 */
            current_stock: number;
            notes?: string;
        };
        UpdateBeanRequest: {
            name?: string;
            origin?: string;
            roast_level?: components["schemas"]["RoastLevel"];
            roast_detail?: components["schemas"]["RoastDetail"];
            /** Format: int32 */
            current_stock?: number;
            notes?: string;
        };
        ListBeansResponse: {
            beans: components["schemas"]["CoffeeBeanResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
        PaginationResponse: {
            /** Format: int64 */
            total: number;
            /** Format: int32 */
            limit: number;
            /** Format: int32 */
            offset: number;
            has_more: boolean;
        };
        DeleteResponse: {
            message: string;
        };
        CreateUsageHistoryRequest: {
            /** Format: date */
            usage_date: string;
            /** Format: int32 */
            quantity: number;
            notes?: string;
        };
        UsageHistoryResponse: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            coffee_bean_id: string;
            /** Format: date */
            usage_date: string;
            /** Format: int32 */
            quantity: number;
            notes?: string;
            /** Format: date-time */
            created_at: string;
        };
        ListUsageHistoryResponse: {
            usages: components["schemas"]["UsageHistoryResponse"][];
            pagination: components["schemas"]["PaginationResponse"];
        };
        ErrorBody: {
            code: string;
            message: string;
            details?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            field: string;
            message: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    registerAnonymous: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description リフレッシュ成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshResult"];
                };
            };
            /** @description トークン無効 */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listBeans: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListBeansResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createBean: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBeanRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeBeanResponse"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getBean: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeBeanResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description アクセス権限なし */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateBean: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBeanRequest"];
            };
        };
        responses: {
            /** @description 更新成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeBeanResponse"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description アクセス権限なし */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteBean: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description アクセス権限なし */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listUsageHistories: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListUsageHistoryResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description アクセス権限なし */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description コーヒー豆が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createUsageHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUsageHistoryRequest"];
            };
        };
        responses: {
            /** @description 作成成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageHistoryResponse"];
                };
            };
            /** @description バリデーションエラー */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description アクセス権限なし */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description コーヒー豆が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 在庫不足 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteUsageHistory: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                usageId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 削除成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResponse"];
                };
            };
            /** @description 認証エラー */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description アクセス権限なし */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description 使用記録が見つかりません */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
